CREATE TABLE IF NOT EXISTS `Projetos` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Titulo` VARCHAR(255) NOT NULL,
    `DataCriacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DataConclusao` DATETIME DEFAULT NULL,
    `IdUsuario` BIGINT NOT NULL,
    PRIMARY KEY (`Id`),
    FOREIGN KEY (`IdUsuario`) REFERENCES `Usuarios`(`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
